name: Auto Building Wine Runner
run-name: ${{ github.actor }} Auto Building Wine Runner 🚀
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building DEB
        env: 
          GUSER: ${{ secrets.GUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          UPLOADURL: ${{ secrets.UPLOADURL }}
        run: |
          # 配置环境
          sudo apt update
          sudo apt install git dpkg-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qt5-qmake -y
          git clone https://github.com/gfdgd-xi/deep-wine-runner
          cd deep-wine-runner
          #make build
          #mv spark-deepin-wine-runner.deb ~
          sudo apt build-dep .
          dpkg-buildpackage -b
          cp spark-deepin-wine-runner_*.deb ~/spark-deepin-wine-runner.deb
      - name: upload result
        uses: actions/upload-artifact@v1
        with:
          name: spark-deepin-wine-runner.deb
          path: /home/runner/spark-deepin-wine-runner.deb
      
      
    