name: Auto Building Wine Runner（pkg）
run-name: ${{ github.actor }} Auto Building Wine Runner（pkg） 🚀
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Building PKG
        env: 
          GUSER: ${{ secrets.GUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          UPLOADURL: ${{ secrets.UPLOADURL }}
        run: |
          # 配置环境
          pacman -Sy
          pacman -S yay git sudo
          pacman -S dpkg qt5-base -y
          yay install
          git clone https://github.com/gfdgd-xi/deep-wine-runner
          cd deep-wine-runner
          make package-deb -j4 
          make package-pkg -j4
          cd ..
          mv spark-deepin-wine-runner*.pkg.tar.zst ../spark-deepin-wine-runner.pkg.tar.zst
      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: spark-deepin-wine-runner.pkg.tar.zst
          path: spark-deepin-wine-runner.pkg.tar.zst
      
    